"""initial

Revision ID: 9c3aabcdbefe
Revises: 34bdc5dd548c
Create Date: 2023-07-19 14:37:47.330406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3aabcdbefe'
down_revision = '34bdc5dd548c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
